export const displayNameFieldMaxLength = 24
export const surnameFieldMaxLength = 32
export const nicknameFieldMaxLength = 16
export const statusFieldMaxLength = 80
export const accountNameMaxFontSize = 30.4
export const accountNameMinFontSize = 20
export const accountStatusMaxFontSize = 15
export const accountStatusMinFontSize = 10.5
export const channelTitleMaxLength = 30
export const channelDescriptionMaxLength = 160
export const channelActionMenuWidth = 280
export const channelActionMenuHeight = 132
export const channelBlockedMenuHeight = 146
export const chatActionMenuWidth = 320
export const chatActionMenuHeight = 290
export const quickFilters = ['Все', '★']
export const channelAvatarTones = ['#8c5738', '#6eb6ff', '#ff8a5b', '#82c9a3', '#f29f67', '#d18fff']
export const accountsStorageKey = 'tinychok.accounts'
export const sessionStorageKey = 'tinychok.session'
export const cookieConsentStorageKey = 'tinychok.cookie-consent'
