import type { TinychokStore } from './store'

export type AppStore = Pick<
  TinychokStore,
  | 'createGroup'
  | 'createManagedChannel'
  | 'deleteDialog'
  | 'deleteDialogHistory'
  | 'deleteDialogMessage'
  | 'deleteGroupMessage'
  | 'deleteManagedChannelPost'
  | 'deleteGroupThreadComment'
  | 'deleteManagedChannel'
  | 'deleteSubscriptionChannelThreadComment'
  | 'deleteSubscriptionChannel'
  | 'getIdentifierByToken'
  | 'getSnapshotByToken'
  | 'inviteGroupMember'
  | 'inviteManagedChannelMembers'
  | 'leaveGroup'
  | 'listTokensByIdentifier'
  | 'markDialogRead'
  | 'markGroupRead'
  | 'markGroupThreadRead'
  | 'markSubscriptionChannelRead'
  | 'markSubscriptionChannelThreadRead'
  | 'openDirectDialog'
  | 'registerAccount'
  | 'reportContact'
  | 'reportSubscriptionChannel'
  | 'requestCode'
  | 'saveSnapshot'
  | 'searchAccounts'
  | 'sendDirectMessage'
  | 'sendGroupMessage'
  | 'sendManagedChannelPost'
  | 'sendGroupThreadComment'
  | 'sendSubscriptionChannelThreadComment'
  | 'setDialogFavorite'
  | 'setDialogPinnedMessage'
  | 'subscribeToGroupThread'
  | 'subscribeToSubscriptionChannelThread'
  | 'unsubscribeFromGroupThread'
  | 'unsubscribeFromSubscriptionChannelThread'
  | 'updateDialog'
  | 'updateGroup'
  | 'updateManagedChannel'
  | 'updateSubscriptionChannel'
  | 'updateSession'
  | 'verifyCode'
>

export type StoreMetadata = {
  bootstrapSource?: 'empty' | 'file' | 'postgres'
  mode: 'file' | 'postgres'
  stateTableName?: string
}
